# Generated by Django 5.2.7 on 2025-11-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='選項文字')),
                ('votes', models.IntegerField(default=0, verbose_name='票數')),
                ('poll_id', models.IntegerField(verbose_name='投票主題編號')),
            ],
        ),
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='投票主題')),
                ('desc', models.TextField(verbose_name='說明')),
                ('created', models.DateField(verbose_name='建立日期')),
            ],
        ),
    ]
